### ISSUE TITLE
Clock configurator is sometimes displayed although multiple components are selected

### ISSUE THREAD

**Issue by SimonBuxx** [SimonBuxx/Linkuit-Studio#117]

**Comment by etorkay** [comment]
Kindly assign some issues to me, I'd like to work on them

**Comment by SimonBuxx** [comment]
Hi @etorkay, feel free to work on anything you want. I'm currently the only one working on the project and I'll try to assign myself to issues before working on them.

**Comment by etorkay** [comment]
Great, I'm exploring the application 
I'll start working on fixing some bugs
